-- compare-before-after-AFTER.sql
SELECT COUNT(*) AS TotalLogs,
  SUM(CASE WHEN UNICODE(SUBSTRING(Message,1,1))=9940 THEN 1 ELSE 0 END) AS BlockTotal,
  SUM(CASE WHEN UNICODE(SUBSTRING(Message,1,1))=9940 AND Message LIKE '%RSI=%' THEN 1 ELSE 0 END) AS RsiBlocks,
  SUM(CASE WHEN UNICODE(SUBSTRING(Message,1,1))=9940 AND Message LIKE '%RR=%'  THEN 1 ELSE 0 END) AS RrBlocks,
  SUM(CASE WHEN UNICODE(SUBSTRING(Message,1,1))=9940 AND Message LIKE '%SLOT%' THEN 1 ELSE 0 END) AS SlotBlocks,
  DATEDIFF(MINUTE,'2026-03-18 18:42:20',GETDATE()) AS DurMin
FROM LiveLogs
WHERE [Timestamp] >= '2026-03-18 18:42:20' AND [Timestamp] <= GETDATE();
